### PR TITLE
Update dependencies to fix installation

### PR DESCRIPTION
**Pull request by verdurin**
I found I needed to apply these dependency updates in `package.json` in order to fix installation errors.

### CODE REVIEW

**Comment by postalservice14** [comment]
:+1:

**Comment by gmcquillan** [comment]
Yeah, this fixes it for me, too. I was just starting to get into this. Thanks so much @verdurin!

**Comment by hakimel** [comment]
Thanks! This commit has been merged into the dev branch: https://github.com/hakimel/reveal.js/commits/dev

The update to socket.io caused the speaker notes and multiplexing plugins to stop working. I've fixed them now and hopefully there's no regression.

c1a7e83d75a917307320acfdcb87a5702109e979
b16bc6fc2e948dedf597004fb99e69d4042daa47

**Comment by p-j** [comment]
Would be great to see it all merged in `master` since currently, the [full setup installation instruction](https://github.com/hakimel/reveal.js#full-setup) is failing without the fix.

:+1: for the quick fix !

**Comment by hakimel** [comment]
Just brought master up to speed. Will release a new version soon.

**Comment by p-j** [comment]
Awesome, if I may suggest another version bump : in `bower.json`
https://github.com/headjs/headjs/releases

Version 0.9.6 leads to 
`bower headjs#~0.9.6       ENORESTARGET No tag found that was able to satisfy ~0.9.6`

I found that using the latest version `1.0.3` didn't broke anything... But I haven't tested it thoroughly.

**Comment by hakimel** [comment]
All set. Looks like head.js was using non-semver tags before 1.0.3 so "0.9.6" was actually "v0.96". I went with 1.0.3 instead.

**Pull request closed without merging**
