### PR TITLE
Adding support for hash linked slideNumber

### PR DESCRIPTION
**Pull request by sean-parent**
There are two changes here -

Make the hash slide numbering match the shown slide so that `slide.html#/3` is slide 3 and not slide 2.

Added an href link to the slide number if shown to make it simple to share a link to a particular slide even when history is not enabled. This also makes it easy to lock to a particular slide when using auto refresh tools while developing.

### CODE REVIEW

**Comment by mschilli87** [comment]
This was suggested before but decided against: https://github.com/hakimel/reveal.js/issues/2067

**Comment by sean-parent** [comment]
Recommendations to proceed?
I could make 1 based hash indexing optional
I could drop 1 based hash indexing and just keep the href link in the slide number
I could make the href link in the slide number optional
Other suggestions?

**Comment by hakimel** [comment]
I think it'd be best to make the 1-based indexing optional to avoid breaking existing content. If you can revise that I'd be happy to merge this in. Thanks!

**Comment by sean-parent** [comment]
One based indexing is now optional (defaults to zero based for compatibility)

**Comment by hakimel** [comment]
Thanks for updating. One more thing, can you change the merge target of the PR to the 'dev' branch? That's the working branch, we merge dev into master when a new version goes out.

**Comment by marcosalpereira** [comment]
There is still something preventing the incorporation of this change?

**Comment by mschilli87** [comment]
@hakimel: If it's just the wrong target branch, you should be able to change that yourself:
https://blog.github.com/2016-08-15-change-the-base-branch-of-a-pull-request/

**Comment by sean-parent** [comment]
Merged to dev branch and resolved conflicts.

**Comment by hakimel** [comment]
Thanks for resolving the conflicts 🙌

**Pull request merged**
