### PR TITLE
resolves #1324 allow display property to be configured

### LINKED ISSUE #1324: Allow display property of visible slide to be configured
The flexbox model is a very useful way to layout slide content. However, at the moment, it's not possible to use the flexbox model for slides because reveal.js is explicitly setting the display CSS property on the current slide to "block". (See https://github.com/hakimel/reveal.js/blob/master/js/reveal.js#L2724).

Please allow the display property of the current slide to be configured so that other slide layouts can be used. In particular, allow the value to be "flex".

I propose the name `display` for this setting.

``` javascript
Reveal.initialize({
  display: 'flex',
  // ...
});
```

An alternative is to detect the original display value using `getComputedStyle` and reuse that value when setting the display CSS property to reveal the current slide.

### PR DESCRIPTION
**Pull request by mojavelinux**
- allow display property apply to current slide to be configured
- ~~set flex-direction to column by default in case flexbox is used~~

### CODE REVIEW

**Comment by mojavelinux** [comment]
I can confirm that setting `display: 'flex'` in the configuration does not affect the appearance of the sample slide deck, either in the HTML or the print view. The benefit, of course, is that flexbox can now be used to position elements on the screen.

**Comment by mojavelinux** [comment]
Actually, there is a small difference. The center alignment no longer works. It's necessary to add `align-items: center` to the CSS to match the original behavior. But, of course, that's really up to the theme author. For that reason, I'm going to back out the change to adding `flex-direction` to `reveal.css`.

**Comment by hakimel** [comment]
Makes sense to allow this to be configured. Your commit has been merged into the dev branch, and I added the new config value to the docs as well.

**Comment by mojavelinux** [comment]
:+1:

**Comment by pstjohn** [comment]
One issue with this approach is that its hard to have vendor prefixes handled appropriately. Specifically for safari, you'd really want.

```css
   display: -webkit-flex;
   display: flex;
```

**Pull request closed without merging**
