### PR TITLE
Do not add video backgrounds to speaker notes.

### PR DESCRIPTION
**Pull request by Suva**
Do not add video backgrounds in speaker notes window as per issue #1036

### CODE REVIEW

**Comment by jeertmans** [comment]
Hello @hakimel, sorry to re-open the discussion, but wouldn't it be better to mute the audio?

I have background-video only slides, and not showing them in the speaker notes makes the view pretty useless. To me, playing videos but muted would make much more sense.

**Comment by drsybren** [comment]
> I have background-video only slides, and not showing them in the speaker notes makes the view pretty useless. To me, playing videos but muted would make much more sense.

I was actually considering writing a bug report that videos don't show in speaker notes, but then I found this report.

**Comment by drsybren** [comment]
You're on fire, thanks!

**Comment by jeertmans** [comment]
Hello @hakimel, do you already know when this will be part of a new release?

**Pull request merged**
