### PR TITLE
Adding one-sided transitions

### PR DESCRIPTION
**Pull request by jammon**
Now the transition isn’t any more „per slide“ but „per movement of a slide“. So the slide can disappear in a different way than it appeared. This makes a more natural changing of the transition style during a talk.
There is an explanation added to README.md.

(This is my first pull request ever, so please be kind if I made any mistakes.)

### CODE REVIEW

**Comment by hakimel** [comment]
This is really great! I'm creating some tests to ensure there's no regression but so far everything is working perfectly. Will merge soon.

**Comment by hakimel** [comment]
Merged!

Should probably also add support for separate in and out background transitions (`data-background-transition`) at some point so its consistent.

**Comment by jammon** [comment]
Great! Thanks for coming back on this!

**Comment by lcrespom** [comment]
Would also be great if you could specify different in and out transition speeds

**Pull request merged**
