### PR TITLE
Fix: multiple image-urls in data-background-image

### PR DESCRIPTION
**Pull request by cmeessen**
Currently, when using the `data-background-image` attribute, the user can only specify one background image. This is, because if a url is given, the whole string given in `data-background-image` is wrapped into `url()`.

This MR allows to use a comma-separated list, e.g.:

```html
<section data-background-image="image1.png, image2.png"></section>
```

Would be happy to see this merged into `dev`.

### CODE REVIEW

**Comment by cmeessen** [comment]
This bug also exists in v3.9. If this version is still maintained, I would also create a MR for this branch.

**Comment by hakimel** [comment]
Looks good, thanks! There's no reason to patch the 3.9 branch.

**Comment by ArtNow198** [comment]
> Looks good, thanks! There's no reason to patch the 3.9 branches.

**Review by sultan801 — CHANGES_REQUESTED** [review]
Hello

**Comment by faxm0dem** [comment]
When I use this feature, only the first image is being displayed. Is there supposed to be a slideshow of backgrounds ?

**Pull request merged**
