### PR TITLE
Add bower.json

### PR DESCRIPTION
**Pull request by teawithfruit**

### CODE REVIEW

**Comment by ovr** [comment]
ping @hakimel

**Comment by maxmeyer** [comment]
would you mind to use https:// instead of git://? This would make using the url via coporate proxies easier.

**Comment by maxmeyer** [comment]
I think you need to make a PR agains `dev` branch. @hakimel Correct?

**Comment by d10** [comment]
Ping?

**Comment by hakimel** [comment]
The bower.json spec that I found (https://github.com/bower/bower.json-spec) doesn't seem to cover many of the fields included in this file, like _originalSource, _release and _resolution.

Also two things that affect this have changed since the PR was opened; the minified files are no longer included in the repo and we're at version 3.0.0.

How does the below look, anything missing or inaccurate?

```json
{
  "name": "reveal.js",
  "version": "3.0.0",
  "main": [
    "lib/js/head.min.js",
    "js/reveal.js",
    "css/reveal.css"
  ],
  "homepage": "http://lab.hakim.se/reveal-js/",
  "license": "MIT",
  "description": "A framework for easily creating beautiful presentations using HTML.",
  "authors": [
    "Hakim El Hattab <hakim.elhattab@gmail.com>"
  ],
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test"
  ]
}
```

**Comment by maxmeyer** [comment]
Looks good. I think `bower` will complain about missing/wrong entries in this file if you try to install it.

**Comment by gion** [comment]
@hakimel since `head.js` isn't actually part of this project, it should be added as a dependency, not placed in the `main` field.

**Comment by hakimel** [comment]
@gion got it, will revise and add that as a dependency

**Comment by gpedro** [comment]
:+1:

**Comment by hakimel** [comment]
Just added a bower file in b390e66c270d4fc26755fc4097e02808ea567721

Give it shot if you can and let me know if it's working correctly or needs to be revised.

**Comment by gion** [comment]
:+1: works ok

**Pull request closed without merging**
