### PR TITLE
Easy audio recording and playback for MOOCs and screencasts

### PR DESCRIPTION
**Pull request by rajgoel**
Hi Hakim,

I just wrapped up a plugin that I have been using for several courses the last semester. The plugin  allows to easily record and playback audio for MOOCs and screencasts. The plugin has two components: the *audio-slideshow.js* component automatically inserts audio files for each slide and fragment, the *slideshow-recorder.js* component allows easy recording of the audio files. 

Please also check out the live [demo](http://courses.telematique.eu/audio-slideshow). 

The plugin is related to or solves issues #472, #701, #724, and #810.

Thanks a lot for providing an excellent starting point for the plugin.

Have a great day
Raj

### CODE REVIEW

**Comment by fghaas** [comment]
@hakimel — just taking the liberty to follow up with this. This is a really useful feature; could it be merged anytime soon?

**Comment by rajgoel** [comment]
Just updated the plugin, so that it uses the default audio player to control the audio slideshow (instead of the previously used <code>autoSlide</code> functionality). I also updated to the most recent RecordRTC.js version.

This should give more intuitive navigation and full control over the audio including (pause, resume, volume control, mute, jump to time). Also playback on Android should work better now.

If you migrate slide decks using previous versions of the plugin please check out the updated [demo](http://courses.telematique.eu/audio-slideshow).

**Comment by rajgoel** [comment]
@idrdex as far as I know Safari does not (yet?) support WebRTC. As long as this doesn't change, Safari cannot be supported

**Comment by rajgoel** [comment]
@fghaas Chrome support on Android is limited by design decisions of Chrome developers (i.e. audio is only played upon user interaction). The recent update should work better on Chrome for Android now (no autoadvancing without audio), however, the user has to press the play button on each slide. Firefox on Android works.

**Comment by hakimel** [comment]
Thanks for the PR @rajgoel. This is a very cool plugin and one that I'm sure is useful to many others. It has a clear use case and the implementation looks great.

The reveal.js repository has started growing too large and hard to maintain so I have decided not to merge plugins directly into it anymore, and to eventually move out the existing plugins to separate repos. Summarized my thoughts on this here: https://github.com/hakimel/reveal.js/wiki/Plugin-Guidelines

That said I'm gonna close this request but I hope you're open to keeping the plugin around in your own repo.

**Comment by rajgoel** [comment]
I just moved the plugin to a seperate repository https://github.com/rajgoel/reveal.js-plugins. All updates to the plugin will be made there.

**Pull request closed without merging**
