### PR TITLE
Fixing spelling typo and GitHub proper camelcase for brand name

### PR DESCRIPTION
**Pull request by omer727**

### CODE REVIEW

**Comment by lirantal** [comment]
+1 good catch

**Comment by IdanCo** [comment]
+1 finally!

**Comment by Delapouite** [comment]
"Flavor and flavour are different spellings of the same word. Flavor is the preferred spelling in the United States, while flavour is the preferred spelling throughout the rest of the English-speaking world" http://grammarist.com/spelling/flavor-flavour/

**Comment by verythorough** [comment]
@Delapouite I don't think anyone would dispute that, but GitHub chose the name for their brand of markdown, and since they're based in the US, they spell it "[GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/)."  I think it's appropriate to match the spelling of the creator.

**Comment by lirantal** [comment]
+1

**Comment by demoneaux** [comment]
@hakimel this seems like a simple doc fix. Should this be merged?

**Comment by hakimel** [comment]
@demoneaux yep, merged it!

**Comment by lirantal** [comment]
+1

**Pull request merged**
