### PR TITLE
support complex markdown

### PR DESCRIPTION
**Pull request by ccqgithub**
support <textarea data-template> `some code` </textarea>

### CODE REVIEW

**Comment by demoneaux** [comment]
What's the use case for this? Including Markdown within HTML tags will cause it to be parsed by the browser first, hence the resulting Markdown might not be suitable for rendering.

**Comment by ccqgithub** [comment]
@demoneaux 
the the html tag maybe appear with the code snippet。
 
```
<script>
// the script expamle in mardown code 
</script>
```

**Comment by demoneaux** [comment]
I believe that escaping the `</script>` closing tag is enough, using something like this should work:

```html
<section>
<script type="text/template">
# Heading

    <script><\/script>
</script>
```

**Comment by ccqgithub** [comment]
that will make highlight troubles, i know escaping can do that, but i will escape all code in the code of md ?
```
<section>
<script type="text/template">
   # Heading
   ` ` `
       <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Document</title>
    </head>
    <body>
      <script></script>
    </body>
    </html>
   ` ` `
</script>
```

**Comment by hakimel** [comment]
Seems like this makes sense. Using a textarea wrapper avoids the conflict with `<script>` without any drawback that I know of.

The commit has been merged into dev, and the readme was updated to recommend using this over `<script type="text/template">`.

**Pull request closed without merging**
