### PR TITLE
Quiz generator plugin - Given an xml describing quiz questions and scori...

### PR DESCRIPTION
**Pull request by EliseWei**
...ng and an optional configurations object, build a scored quiz with reveal.js slides.

### CODE REVIEW

**Comment by oxhey** [comment]
how do i use thsi with a presentation?

**Comment by EliseWei** [comment]
I intended it to create an independent quiz, and so far I've built a new .html file for each quiz with a link out from a presentation, when needed. But let me investigate getting this to work inside an existing reveal slideshow. Good thought, thanks!

**Comment by oxhey** [comment]
From what iv seen trying to get it to work , by adding in some sections into teh quiz template , the quiz fails to load / the presentation failes to move

**Comment by EliseWei** [comment]
Ok, I just pushed up a small update to ensure that quiz navigation functions either in the vertical or horizontal.
I'm not entirely sure what you mean about adding sections to the quiz template (html or xml?), but I'm guessing the issue you're seeing has to do with the fact that my demo html file has the reveal config set to disallow keyboard or click navigation.
If you turn those back on, a presentation will work with the quiz embedded, but you will also be able to navigate within the quiz without responding to all questions.

Another possible issue has to do with setting the target selector. I found that adding an id to a specific section within a presentation and then targeting that id for quiz insertion works fine. In the example below, quizInit targets '#quiz-target'.
```html
  <div class="slides">
    <section>
      <h3>Slide 1</h3>
    </section>
    <section id="quiz-target">
    </section>
    <section>
      <h3>Slide 3</h3>
    </section>
  </div>
```

**Comment by oxhey** [comment]
By sections i mean slides

**Comment by EliseWei** [comment]
Cool. It seemed to work when structured, targeted, and configured as described above. Quiz successfully embedded as sub-slides between other slides.

**Comment by oxhey** [comment]
kool , ill take a look at it tomorrow

**Comment by hakimel** [comment]
This looks great @EliseWei! However I've decided not to merge any more plugins directly into the main repository since it's making reveal.js increasingly difficult to maintain. Existing plugins will eventually be moved out as well.

I hope you'll still maintain the plugin in your branch and please feel free to add it to the plugins page https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware

**Pull request closed without merging**
