### PR TITLE
use native CSS vars from exposer

### PR DESCRIPTION
**Pull request by Shogoki**
just created this change according to my request in #2739 
This uses the already exposed CSS Variables in the theme template instead of the SASS vars. we´re still initializing the CSS Vars with the Values from SASS, so it should be compatible.

This allows us to easy overwrite theme vars without building a custom theme.

### CODE REVIEW

**Comment by Shogoki** [comment]
As an example how this could be used.

in Index.html
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
    />
    <title>reveal.js</title>
    <link rel="stylesheet" href="../dist/reset.css" />
    <link rel="stylesheet" href="../dist/reveal.css" />
    <link rel="stylesheet" href="../dist/theme/black.css" />
    <link rel="stylesheet" href="theme-customization.css" />

    <!-- Theme used for syntax highlighting of code -->
    <link rel="stylesheet" href="../plugin/highlight/monokai.css" />
  </head>
  <body>
    <div class="reveal">
      <div class="slides">
        <section
          data-markdown="slides.md"
          data-separator="^\n---\n$"
          data-separator-vertical="^\n\|\|\|\n$"
        ></section>
      </div>
    </div>

    <script type="module">
      import Reveal from "../dist/reveal.esm.js";
      import Markdown from "../plugin/markdown/markdown.esm.js";
      import Highlight from "../plugin/highlight/highlight.esm.js";
      import Notes from "../plugin/notes/notes.esm.js";
      import Math from "../plugin/math/math.esm.js";
      Reveal.initialize({
        plugins: [Markdown, Highlight, Notes, Math],
        math: {
          mathjax:
            "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js",
          config: "TeX-AMS_HTML-full",
        },
      });
    </script>
  </body>
</html>

```

with the following in theme-customization.css

```css
:root {
    --background-color:  #ffffff;
    --main-color:  #000000;
    --heading-color: rgb(31, 2, 136);
    --main-font-size: 16pt;
}
.test {
    --heading-color: rgb(29, 153, 60);
}
```
overwriting the vars in `:root` I can customize my defaults, but can also super easy adjust it only for specific classes/slides like in the `test`class which is can be quite handy.

Assuming a slides.md file with the following Content:

```markdown

# Test Slide 1

some content

---

# Test Slide2
<!-- .slide:  data-state="test" -->
some other content

|||

# Horizontal Test-Slide

some content

**Comment by PK-Patomsiri** [comment]
> just created this change according to my request in #2739 
> This uses the already exposed CSS Variables in the theme template instead of the SASS vars. we´re still initializing the CSS Vars with the Values from SASS, so it should be compatible.
> 
> This allows us to easy overwrite theme vars without building a custom theme.

**Comment by Katy-kaboom101** [comment]
Hi I apologize for just jumping on here but I'm getting hacked by my sister because my father passed away in September and she's angry at me because he didn't leave her anything. This is all I know if it makes sense maybe you can help me stop her. Yes I've put in a request for GitHub to help me with no results. I've closed 2 accounts I didn't open. I don't understand this stuff it's been driving me crazy and making me sick. imageimagethis is from my boyfriends phoneimageimageimageimageimagefrom my computer that was brand new before I had to go to Oregon to Bury ￼my father￼.image 
It's been going on for a long time she was a dental assistant so she's using medical coding too. I have tons of screenshots I've tried to understand what's going on it just doesn't click for me. Thank you for any help 
Katy Orsborn

**Review by flooki009 — APPROVED** [review]

**Comment by edemaine** [comment]
Any chance of this PR being revitalized and approved? I just wanted to change the font from a built-in theme, and this would make it really easy to do so.

**Comment by hakimel** [comment]
This has been merged—thanks!

**Pull request merged**
