### PR TITLE
Issue #1105: Keyboard shortcut to skip forward/back over fragments

### PR DESCRIPTION
**Pull request by kellyk**

### CODE REVIEW

**Comment by niccnacc** [comment]
Looks really well implemented. Without having tried it, is there a way to automatically activate "hard change" commands locally, if the points were already shown? This would make it a production quality treat!
Thanks for your work!

**Comment by bcokert** [comment]
Shift+right/left works as expected. Shift+up/down skips to the end of the fragments list, instead of to the next slide, which is a bit unexpected. Otherwise, works great! Used it in my last presentation (where I really just wanted let+right anyways).

**Comment by bcouetil** [comment]
Hello, would love to have this feature, when is it expected to be merged ?

**Comment by Lomacar** [comment]
PLEASE MERGE.

**Comment by hakimel** [comment]
Very sorry about never getting back to you on this @kellyk. I'm perpetually behind on issues and PRs.

As of 90bbe8be4f12ec56723a335d36f9be984ef7ed03, holding alt + pressing any navigation shortcut (arrows, space, n, p etc) will now skip fragments. Shift+left/right were already used for jumping to the first/last slide we couldn't use that modifier. More info: https://github.com/hakimel/reveal.js/issues/1105#issuecomment-913565307

**Pull request closed without merging**
