### PR TITLE
add option to mute background videos

### PR DESCRIPTION
**Pull request by oslego**
This pull request adds the `muted` property to a video element that is used as a slide background. 

Using the `data-background-video-muted` attribute together with `data-background-video` mutes the video. Useful for videos that can't be edited.

### CODE REVIEW

**Comment by hakimel** [comment]
Great addition. Any chance you can remove the whitespace changes to avoid conflicts? We basically want these changes: https://github.com/oslego/reveal.js/commit/8bbc2971acafafdb6194efe372663d8ec59b6f0a?w=1

**Comment by oslego** [comment]
I made the required changes and rebased from latest `dev` branch. Does this look gook?

**Comment by hakimel** [comment]
Weird, it looks like those whitespace changes still snuck their way in but I went ahead and merged this anyway. Thanks for the PR!

**Comment by oslego** [comment]
I think that happened because of a merge I did with my previously pushed
branch. I'm sorry! End-of-line whitespace removal happens automatically in
my Atom editor. I disabled that for future work.

Thanks for accepting the PR!

**Pull request merged**
