### PR TITLE
.gitignore - ignore package-lock.json file

### PR DESCRIPTION
**Pull request by keradus**
Ignore lock file of newer node versions

### CODE REVIEW

**Comment by hakimel** [comment]
Thanks, this has been merged into the dev branch @ https://github.com/hakimel/reveal.js/commits/dev

**Comment by keradus** [comment]
sorry, my bad with target branch.
thanks !

**Comment by bnjmnt4n** [comment]
Hi what's the rationale for this? AFAIK, package-lock.json should be included in the repository as recommended by npm.

**Comment by keradus** [comment]
it shall for app, not for library

**Pull request closed without merging**
